[package]
name = "rust_quiz_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fmt = "0.1.0"
rand = "0.8.5"
serde = { version = "1.0.195", features = ["derive"] }
toml = "0.8.8"
