quiz_name = "How well do you know Jordy?"
[[questions]]
    question = "What is Jordy's Favorite book?" 
    answers = [
    "The Alchemist",
    "The Odyssey",
    "The Divine Comedy: Inferno",
    "The Hitchhikers Guide to the Galaxy",
    ]
    correct_answer = 1

[[questions]]
    question = "Jordy gets stabbed, what happens?" 
    answers = [
    "Nothing.",
    "He dies.",
    "He fights back.",
    "He stabs them back.",
    ]
    correct_answer = 2
    
[[questions]]
    question = "Which of the following would Jordy prefer to be locked in deadly combat with?" 
    answers = [
    "7 Ducks",
    "4 Raccoons",
    "3 Capybara",
    "2 Flamingos",
    ]
    correct_answer = 1

[[questions]]
    question = "What is Jordy's Favorite anime?" 
    answers = [
    "School Rumble",
    "Cowbow Bebop",
    "Full Metal Alchemist",
    "Overlord",
    ]
    correct_answer = 1

[[questions]]
    question = "In the thought experiment named The Ship of Theseus, at what point would Jordy consider the ship a new ship?" 
    answers = [
    "Anything > 0%",
    "50%",
    "100%",
    "Never",
    ]
    correct_answer = 4 

[[questions]]
    question = "What is Jordy's Favorite audible?" 
    answers = [
    "Project Hail Mary",
    "Ready Player One",
    "The Name of the Wind",
    "The Way of Kings",
    ]
    correct_answer = 1

[[questions]]
    question = "In what situation would Jordy rather find himself in?" 
    answers = [
    "Alien Invasion",
    "Zombie Virus Outbreak",
    "The Purge",
    "Nuclear Winter",
    ]
    correct_answer = 4

[[questions]]
    question = "According to speculations formed by Julius, EE Teams first co-op, what criminal organization is Jordy a part of?" 
    answers = [
    "Solomon Organization",
    "Crips",
    "MS-13",
    "ISIS",
    ]
    correct_answer = 4

[[questions]]
    question = "You ask Jordy how hes doing, what does he say?" 
    answers = [
    "Good How are you?",
    "eh, you know how it is.",
    "Pretty Alright.",
    "Same old, you know.",
    ]
    correct_answer = 3

[[questions]]
    question = "As a surprise, you hand Jordy a beer, what does he say?" 
    answers = [
    "Sheeeeesh! Thank you!",
    "Oho, thank you sir!",
    "Oh shit, Thanks!!",
    "Oh, no thank you.",
    ]
    correct_answer = 2

[[questions]]
    question = "Who is Jordy's favorite Greek God?" 
    answers = [
    "Dionysus",
    "Hephaestus",
    "Hermes",
    "Hades",
    ]
    correct_answer = 4

[[questions]]
    question = "What are Jordy's thoughts on Aliens?"
    answers = [
    "No aliens, no way.",
    "We have to be the first. I think we would have heard or seen something by now if theres others, or they would have seen us.",
    "Maybe at some point, maybe not. I really don't know if they are out there, but I certainly hope not.",
    "They are out there, theres gotta be something. The universe is far to vast to have nothing.",
    ]
    correct_answer = 4

[[questions]]
    question = "What is a movie that Jordy would be down to watch at any time?" 
    answers = [
    "Forrest Gump",
    "Pirates of the Caribbean",
    "Dances with Wolves",
    "The Lord of the Rings: The Return of the King",
    ]
    correct_answer = 2

[[questions]]
    question = "What type of Music does Jordy like the least?" 
    answers = [
    "Country",
    "Lo-fi",
    "Trap",
    "Dubstep",
    ]
    correct_answer = 3

[[questions]]
    question = "What was Jordy known for when he was an infant?" 
    answers = [
    "Wanting Solitute",
    "Crying all the time",
    "Being aggressive",
    "Nothing, he was an infant.",
    ]
    correct_answer = 1

[[questions]]
    question = "What was Jordy most likley doing on January 1st, 2024 at 12:03 am?" 
    answers = [
    "Sleeping",
    "Eating Grapes",
    "Partying",
    "Drinking",
    ]
    correct_answer = 2

[[questions]]
    question = "What type of phobia does Jordy have? "
    answers = [
    "Acrophobia",
    "Samhainophobia",
    "Agoraphobia",
    "Melissophobia",
    ]
    correct_answer = 4

[[questions]]
    question = "Best Pizza place in existance in Jordy's opinion?" 
    answers = [
    "Santarpio's",
    "Hotbox",
    "Prince Palace",
    "Otto",
    ]
    correct_answer = 3

[[questions]]
    question = "You and Jordy sit in a time machine and you tell him to set a time period to go visit. What does he pick?" 
    answers = [
    "Mesozoic",
    "Classical Antiquity",
    "Early Modern Period",
    "High Middle Ages",
    ]
    correct_answer = 2

[[questions]]
    question = "What is Jordy's Smash Bros main?" 
    answers = [
    "Robin",
    "Ganondorf",
    "Ike",
    "Joker",
    ]
    correct_answer = 2

[[questions]]
    question = "What is Jordy's Favorite Legend of Zelda Game?" 
    answers = [
    "Ocarina of Time",
    "Twilight Princess",
    "Majoras Mask",
    "Breath of the Wild",
    ]
    correct_answer = 3

[[questions]]
    question = "What was Jordy doing on September 8th, 2022?" 
    answers = [
    "Working.",
    "👀",
    "Drinking Tea.",
    "Playing video games.",
    ]
    correct_answer = 1

[[questions]]
    question = "What was Jordy's Favorite board game?" 
    answers = [
    "Wingspan",
    "Dominion",
    "Disney Villanous",
    "Dominos",
    ]
    correct_answer = 2

[[questions]]
    question = "Jordy throws a snowball with an initail velocity of 15 m/s at angle 10 degrees to the horizonal. How long will the snowball stay in the air, assuming it hits the ground at the same height it was launched?" 
    answers = [
    "2.15 seconds",
    "0.53 seconds",
    "1.43 seconds",
    "0.23 seconds",
    ]
    correct_answer = 2

[[questions]]
    question = "What was Jordy's prefered meal in elemetry school?" 
    answers = [
    "Peanut butter and Jelly",
    "Chicken Nuggets",
    "Hot Pocket",
    "Peanut butter and Fluff",
    ]
    correct_answer = 4

[[questions]]
    question = "You have a dream of being drafted in the army in the middle ages. You and Jordy are in the barracks readying for battle. What weapon does Jordy hold?" 
    answers = [
    "Morning Star",
    "Halberd",
    "Long Sword",
    "Katana",
    ]
    correct_answer = 4

[[questions]]
    question = "You and Jordy appear in a fantasy world, what 'class' is Jordy most likly to be/seek out?" 
    answers = [
    "Wizard",
    "Barbarian",
    "Rogue",
    "Bard",
    ]
    correct_answer = 1

[[questions]]
    question = "What is Jordy's Preferred method for Human Extinction?" 
    answers = [
    "Nuclear War",
    "Extraterrestrial Invasion",
    "Cosmic Catastrophe",
    "Climate Change",
    ]
    correct_answer = 3