quiz_name = "Jordy!"
[[questions]]
    question = "What is a movie that Jordy would be down to watch at any time?" 
    answers = [
    "Forrest Gump",
    "Pirates of the Caribbean",
    "Dances with Wolves",
    "The Lord of the Rings: The Return of the King",
    ]
    correct_answer = 2

[[questions]]
    question = "What type of Music does Jordy like the least?" 
    answers = [
    "Country",
    "Lo-fi",
    "Trap",
    "Dubstep",
    ]
    correct_answer = 3

[[questions]]
    question = "What was Jordy known for when he was an infant?" 
    answers = [
    "Wanting Solitute",
    "Crying all the time",
    "Being aggressive",
    "Nothing, he was an infant.",
    ]
    correct_answer = 1